---
- name: Start all containers
  shell: "docker-compose up -d"
  args:
    chdir: "{{ app_path }}"

- name: Wait for container to be ready
  pause:
    seconds: 30

- name: Execute database migrations and seeders.
  shell: "docker exec -i webserver1 python3 {{ item }}"
  args:
    chdir: "{{ app_path }}"
  loop:
    - db_migrations.py
    - db_seed.py
