---
# System
bin_dir: "/usr/local/bin"
default_executable: "/bin/bash"
locale: en_US.UTF-8
timezone: "America/Santo_Domingo"

system_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - python3-pip
  - virtualenv
  - python3-setuptools
