---
- name: Update locale variables to environment.
  lineinfile:
    path: "{{ item.file }}"
    regexp: "{{ item.reg }}"
    line: "{{ item.line }}"
  become: yes
  loop:
    - {
        file: "/etc/environment",
        reg: "^LC_ALL=",
        line: "LC_ALL=en_US.UTF-8"
      }
    - {
        file: "/etc/locale.gen",
        reg: "^en_US.UTF-8",
        line: "en_US.UTF-8 UTF-8"
      }

- name: Set system locale to {{ locale }}.
  community.general.locale_gen:
    name: "{{ locale }}"
    state: present
  become: yes

- name: Set system timezone to {{ timezone }}.
  community.general.timezone:
    name: "{{ timezone }}"
  become: yes
