Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "webserver"
  config.vm.network "private_network", ip: "192.168.56.100"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provision "ansible", playbook: "webserver.yml"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
end
